// Données mock pour le développement local (sans PostgreSQL ni JWT)
// Réactiver prisma/db dans les routes API pour utiliser la vraie base de données.

const day = 24 * 60 * 60 * 1000
const now = Date.now()

export const MOCK_TOKEN = 'mock-local-dev-token'

export const mockUsers = {
  admin: {
    id: 'user-admin',
    nom: 'Admin',
    prenom: 'Dice',
    email: 'admin@dice.com',
    telephone: '0123456789',
    sexe: 'M',
    role: 'admin',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  user: {
    id: 'user-test',
    nom: 'Dupont',
    prenom: 'Jean',
    email: 'user@dice.com',
    telephone: '0987654321',
    sexe: 'M',
    role: 'user',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
}

export let mockEvents = [
  {
    id: 'event-1',
    title: 'Atelier React Avancé',
    description: 'Maîtrisez les concepts avancés de React pour créer des applications performantes avec des hooks personnalisés, le context API et le lazy loading.',
    type: 'atelier',
    price: 149.99,
    promotion: false,
    originalPrice: null,
    date: new Date(now + 7 * day).toISOString(),
    duration: 8,
    location: 'Paris, France',
    instructor: 'Jean Dupont',
    totalSeats: 20,
    availableSeats: 20,
    image: '/images/events/react-workshop.jpg',
    status: 'upcoming',
    tickets: [],
  },
  {
    id: 'event-2',
    title: 'Conférence IA & Machine Learning',
    description: 'Découvrez les dernières avancées en intelligence artificielle et machine learning, avec des cas pratiques et des démonstrations en direct.',
    type: 'conference',
    price: 299.99,
    promotion: true,
    originalPrice: 399.99,
    date: new Date(now + 14 * day).toISOString(),
    duration: 6,
    location: 'Lyon, France',
    instructor: 'Marie Martin',
    totalSeats: 50,
    availableSeats: 50,
    image: '/images/events/ai-conference.jpg',
    status: 'upcoming',
    tickets: [],
  },
  {
    id: 'event-3',
    title: 'Séminaire DevOps et Cloud',
    description: 'Apprenez à déployer et gérer vos applications avec les outils DevOps modernes : Docker, Kubernetes, CI/CD, et monitoring.',
    type: 'seminaire',
    price: 199.99,
    promotion: false,
    originalPrice: null,
    date: new Date(now + 21 * day).toISOString(),
    duration: 12,
    location: 'Bordeaux, France',
    instructor: 'Pierre Dubois',
    totalSeats: 30,
    availableSeats: 30,
    image: '/images/events/devops-seminar.jpg',
    status: 'upcoming',
    tickets: [],
  },
  {
    id: 'event-4',
    title: 'Atelier Next.js & TypeScript',
    description: 'Développez des applications modernes avec Next.js 14 et TypeScript, en utilisant le App Router et les Server Components.',
    type: 'atelier',
    price: 179.99,
    promotion: true,
    originalPrice: 229.99,
    date: new Date(now + 28 * day).toISOString(),
    duration: 10,
    location: 'Toulouse, France',
    instructor: 'Sophie Leroy',
    totalSeats: 25,
    availableSeats: 25,
    image: '/images/events/nextjs-workshop.jpg',
    status: 'upcoming',
    tickets: [],
  },
  {
    id: 'event-5',
    title: 'Conférence Web Performance',
    description: 'Optimisez la performance de vos applications web avec les dernières techniques et outils d\'analyse.',
    type: 'conference',
    price: 249.99,
    promotion: false,
    originalPrice: null,
    date: new Date(now + 35 * day).toISOString(),
    duration: 4,
    location: 'Paris, France',
    instructor: 'Thomas Richard',
    totalSeats: 40,
    availableSeats: 40,
    image: '/images/events/performance-conference.jpg',
    status: 'upcoming',
    tickets: [],
  },
  {
    id: 'event-6',
    title: 'Séminaire Architecture Microservices',
    description: 'Concevez et implémentez des architectures microservices robustes avec Spring Boot, Docker et Kubernetes.',
    type: 'seminaire',
    price: 349.99,
    promotion: false,
    originalPrice: null,
    date: new Date(now + 42 * day).toISOString(),
    duration: 16,
    location: 'Lyon, France',
    instructor: 'Michel Dupuis',
    totalSeats: 35,
    availableSeats: 35,
    image: '/images/events/microservices-seminar.jpg',
    status: 'upcoming',
    tickets: [],
  },
]

export let mockTickets = [
  {
    id: 'ticket-1',
    code: '12345678',
    userId: 'user-test',
    eventId: 'event-1',
    status: 'pending',
    pricePaid: 134.99,
    datePurchase: new Date(now - day).toISOString(),
    event: null,
    user: { id: 'user-test', nom: 'Dupont', prenom: 'Jean', email: 'user@dice.com' },
  },
  {
    id: 'ticket-2',
    code: '87654321',
    userId: 'user-test',
    eventId: 'event-2',
    status: 'validated',
    pricePaid: 269.99,
    datePurchase: new Date(now - 2 * day).toISOString(),
    event: null,
    user: { id: 'user-test', nom: 'Dupont', prenom: 'Jean', email: 'user@dice.com' },
  },
]

export let mockNotifications = [
  {
    id: 'notif-1',
    userId: 'user-test',
    type: 'new_event',
    title: 'Nouvelle formation disponible',
    message: 'Atelier React Avancé - Réservez dès maintenant !',
    eventId: 'event-1',
    read: false,
    createdAt: new Date(now - day).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'user-test',
    type: 'update_event',
    title: 'Mise à jour de formation',
    message: 'La formation "DevOps et Cloud" a été mise à jour.',
    eventId: 'event-3',
    read: false,
    createdAt: new Date(now - 2 * day).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'user-test',
    type: 'reminder',
    title: 'Rappel de formation',
    message: 'Votre formation "IA & Machine Learning" commence dans 3 jours.',
    eventId: 'event-2',
    read: true,
    createdAt: new Date(now - 3 * day).toISOString(),
  },
]

// Hydrate ticket relations
mockTickets = mockTickets.map((ticket) => ({
  ...ticket,
  event: mockEvents.find((e) => e.id === ticket.eventId) || null,
}))

export function findMockUserByEmail(email) {
  return Object.values(mockUsers).find((u) => u.email === email) || null
}
